### ISSUE TITLE
No train code released?

### ISSUE THREAD

**Issue by justinday123** [yael-vinker/live_sketch#5]
Thank you for your nice work. Is there no train code released?

**Comment by rinongal** [comment]
The code in `animate_svg.py` and the instructions in [the readme](https://github.com/yael-vinker/live_sketch?tab=readme-ov-file#generate-a-video-woman_artist-art) **are** the training code. 

This work is a per-video optimization method. There's no large scale training involved in our paper. The text-to-video prior is just an off-the-shelf video model from HuggingFace.
